### ISSUE TITLE
Quick Start

### ISSUE THREAD

**Issue by rlebron-bioinfo** [guigolab/FA-nf#1]
Hi,

Nice pipeline. Could you please provide step by step instructions on how to build the image (including third-party images like **sigtarp** and **ipscan**), how to set up the pipeline and how to run it with the test datasets? I'm trying to do it myself, but mostly I'm having problems building the **sigtarp** and **ipscan** images. Thanks in advance.

Best regards,
Ricardo Lebrón

**Comment by toniher** [comment]
Hello Ricardo,
first of all, apologies for the delay answering you. I have improved a bit the documentation of [Interproscan](https://github.com/biocorecrg/interproscan_docker) and [Sigtarp](https://github.com/biocorecrg/sigtarp_docker) container images. Let me know if you get stuck at some point.
Including privative software in these cases may not be straightforward, since you need to get each different program through their specific ways before. In any case, since this can be an issue to other potential users, I have included the option to generate an Interproscan open image, and I also have modified the pipeline to include an option for skipping analyses with Signal & TargetP (sigtarp container images).

**Comment by toniher** [comment]
Several other improvements were made in the Interproscan image, and external repositories have been added as submodules in the repository. Please do not hesitate to open any additional ticket for any other specific issue.
